
MESSAGE(STATUS "Searching for OIS library...")

FIND_PATH(OIS_INCLUDE_DIR OIS/OIS.h)

find_path(OIS_INCLUDE_DIR NAMES OIS.h
  PATHS ${OIS_PREFIX_PATH}
  PATH_SUFFIXES OIS include includes)

if(NOT OIS_INCLUDE_DIR)
  find_path(OIS_INCLUDE_DIR NAMES OIS.h
    PATHS ${OIS_PREFIX_PATH}
    PATH_SUFFIXES OIS include include/OIS)
endif()

FIND_LIBRARY(OIS_LIBRARY NAMES OIS)

IF (OIS_INCLUDE_DIR AND OIS_LIBRARY)
  SET(OIS_FOUND TRUE)
ENDIF (OIS_INCLUDE_DIR AND OIS_LIBRARY)

IF (OIS_FOUND)
  set(OIS_LIBRARIES ${OIS_LIBRARY})
  if (UNIX AND NOT ANDROID)
    set(OIS_LIBRARIES ${OIS_LIBRARIES} X11)
  endif ()
  IF (NOT OIS_FIND_QUIETLY)
    MESSAGE(STATUS "Found OIS: ${OIS_LIBRARY}")
    MESSAGE(STATUS "Found OIS: ${OIS_LIBRARIES}")
    MESSAGE(STATUS "Found OIS: ${OIS_INCLUDE_DIR}")
  ENDIF (NOT OIS_FIND_QUIETLY)

ELSE (OIS_FOUND)

  # fatal error if OIS is required but not found
  IF (OIS_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find OIS")
  ENDIF (OIS_FIND_REQUIRED)

ENDIF (OIS_FOUND)
